"""
Auto-generated configuration schema components from shared_config.py
DO NOT EDIT THIS FILE MANUALLY - it will be overwritten on build
"""

from typing import TypedDict, Dict, Any, Union
from enum import Enum

from shared_config import CONFIG_SCHEMA_DEF, ConfigFieldType

# Field name constants for type-safe access
DLL = "dll"
ALLOW_FP16 = "allow_fp16"
SCALING_ENABLED = "scaling_enabled"
SCALING_METHOD = "scaling_method"
SCALING_FACTOR = "scaling_factor"
SCALING_SUPERSAMPLING = "scaling_supersampling"
SCALING_SHARPNESS = "scaling_sharpness"
FRAME_GENERATION_PROVISIONED = "frame_generation_provisioned"
FRAME_GENERATION_ENABLED = "frame_generation_enabled"
AUTOMATIC_DOCK_MODE = "automatic_dock_mode"
FG_BACKEND = "fg_backend"
OPTISCALER_PROXY = "optiscaler_proxy"
FRAME_GENERATION_REFRESH_THRESHOLD = "frame_generation_refresh_threshold"
BASE_FPS_CAP = "base_fps_cap"
MULTIPLIER = "multiplier"
ADAPTIVE = "adaptive"
ADAPTIVE_AUTO_BASE_FPS_CAP = "adaptive_auto_base_fps_cap"
ADAPTIVE_FRACTIONAL_REAL_FRAME_PRIORITY = "adaptive_fractional_real_frame_priority"
TARGET_FPS = "target_fps"
ADAPTIVE_MAX_MULTIPLIER = "adaptive_max_multiplier"
ADAPTIVE_STABLE_CADENCE = "adaptive_stable_cadence"
GAMESCOPE_VRR_MODE = "gamescope_vrr_mode"
DYNAMIC_CADENCE_RECOVERY = "dynamic_cadence_recovery"
DYNAMIC_CADENCE_PROBE_INTERVAL_SECONDS = "dynamic_cadence_probe_interval_seconds"
ULTRA_PERFORMANCE = "ultra_performance"
FLOW_SCALE = "flow_scale"
PERFORMANCE_MODE = "performance_mode"
PACING = "pacing"
ACTIVE_IN = "active_in"
GPU = "gpu"
DISABLE_MAKO = "disable_mako"
DISABLE_HDR_EXPOSURE = "disable_hdr_exposure"
GAMESCOPE_WSI_COMPATIBILITY = "gamescope_wsi_compatibility"
SWAPCHAIN_IMAGE_COUNT_COMPATIBILITY = "swapchain_image_count_compatibility"
EXTERNAL_VULKAN_LAYER = "external_vulkan_layer"
VKBASALT_SHARPENING = "vkbasalt_sharpening"
VKBASALT_SHARPNESS = "vkbasalt_sharpness"
VKBASALT_DLS_DENOISE = "vkbasalt_dls_denoise"
VKBASALT_ANTIALIASING = "vkbasalt_antialiasing"
VKBASALT_SHADER = "vkbasalt_shader"
DISABLE_STEAMDECK_MODE = "disable_steamdeck_mode"
ENABLE_ZINK = "enable_zink"
FORCE_ALSA_AUDIO = "force_alsa_audio"


class ConfigurationData(TypedDict):
    """Type-safe configuration data structure - AUTO-GENERATED"""
    dll: str
    allow_fp16: bool
    scaling_enabled: bool
    scaling_method: str
    scaling_factor: float
    scaling_supersampling: bool
    scaling_sharpness: float
    frame_generation_provisioned: bool
    frame_generation_enabled: bool
    automatic_dock_mode: bool
    fg_backend: str
    optiscaler_proxy: str
    frame_generation_refresh_threshold: int
    base_fps_cap: int
    multiplier: int
    adaptive: bool
    adaptive_auto_base_fps_cap: bool
    adaptive_fractional_real_frame_priority: str
    target_fps: int
    adaptive_max_multiplier: int
    adaptive_stable_cadence: bool
    gamescope_vrr_mode: str
    dynamic_cadence_recovery: bool
    dynamic_cadence_probe_interval_seconds: float
    ultra_performance: bool
    flow_scale: float
    performance_mode: bool
    pacing: str
    active_in: str
    gpu: str
    disable_mako: bool
    disable_hdr_exposure: bool
    gamescope_wsi_compatibility: bool
    swapchain_image_count_compatibility: bool
    external_vulkan_layer: str
    vkbasalt_sharpening: str
    vkbasalt_sharpness: float
    vkbasalt_dls_denoise: float
    vkbasalt_antialiasing: str
    vkbasalt_shader: str
    disable_steamdeck_mode: bool
    enable_zink: bool
    force_alsa_audio: bool


class ConfigurationPatch(TypedDict, total=False):
    """Validated partial profile update - AUTO-GENERATED"""
    dll: str
    allow_fp16: bool
    scaling_enabled: bool
    scaling_method: str
    scaling_factor: float
    scaling_supersampling: bool
    scaling_sharpness: float
    frame_generation_provisioned: bool
    frame_generation_enabled: bool
    automatic_dock_mode: bool
    fg_backend: str
    optiscaler_proxy: str
    frame_generation_refresh_threshold: int
    base_fps_cap: int
    multiplier: int
    adaptive: bool
    adaptive_auto_base_fps_cap: bool
    adaptive_fractional_real_frame_priority: str
    target_fps: int
    adaptive_max_multiplier: int
    adaptive_stable_cadence: bool
    gamescope_vrr_mode: str
    dynamic_cadence_recovery: bool
    dynamic_cadence_probe_interval_seconds: float
    ultra_performance: bool
    flow_scale: float
    performance_mode: bool
    pacing: str
    active_in: str
    gpu: str
    disable_mako: bool
    disable_hdr_exposure: bool
    gamescope_wsi_compatibility: bool
    swapchain_image_count_compatibility: bool
    external_vulkan_layer: str
    vkbasalt_sharpening: str
    vkbasalt_sharpness: float
    vkbasalt_dls_denoise: float
    vkbasalt_antialiasing: str
    vkbasalt_shader: str
    disable_steamdeck_mode: bool
    enable_zink: bool
    force_alsa_audio: bool


class WrapperSettingsData(TypedDict):
    """Canonical launcher-only profile settings - AUTO-GENERATED"""
    automatic_dock_mode: bool
    fg_backend: str
    optiscaler_proxy: str
    disable_mako: bool
    disable_hdr_exposure: bool
    gamescope_wsi_compatibility: bool
    external_vulkan_layer: str
    vkbasalt_sharpening: str
    vkbasalt_sharpness: float
    vkbasalt_dls_denoise: float
    vkbasalt_antialiasing: str
    vkbasalt_shader: str
    disable_steamdeck_mode: bool
    enable_zink: bool
    force_alsa_audio: bool


def get_script_generation_logic():
    """Return the script generation logic as a callable"""
    def generate_script_lines(config):
        lines = []
        if config.get("disable_mako", False):
            lines.append("export DISABLE_MAKO=1")
        if config.get("disable_hdr_exposure", False):
            lines.append("export MAKO_DISABLE_HDR_EXPOSURE=1")
        external_vulkan_layer = config.get("external_vulkan_layer", "")
        lines.append(f"export MAKO_EXTERNAL_VULKAN_LAYER={external_vulkan_layer}")
        if config.get("disable_steamdeck_mode", False):
            lines.append("export SteamDeck=0")
        if config.get("enable_zink", False):
            lines.append("export __GLX_VENDOR_LIBRARY_NAME=mesa")
            lines.append("export MESA_LOADER_DRIVER_OVERRIDE=zink")
            lines.append("export GALLIUM_DRIVER=zink")
        if config.get("force_alsa_audio", False):
            lines.extend([
                "export SDL_AUDIODRIVER=alsa",
                'case ";${WINEDLLOVERRIDES:-};" in',
                '    *";winepulse.drv=d;"*) ;;',
                '    *) export WINEDLLOVERRIDES="${WINEDLLOVERRIDES:+$WINEDLLOVERRIDES;}winepulse.drv=d" ;;',
                "esac",
                'case ";${WINEDLLOVERRIDES:-};" in',
                '    *";winealsa.drv=b;"*) ;;',
                '    *) export WINEDLLOVERRIDES="${WINEDLLOVERRIDES:+$WINEDLLOVERRIDES;}winealsa.drv=b" ;;',
                "esac",
            ])
        return lines
    return generate_script_lines


ALL_FIELDS = ['dll', 'allow_fp16', 'scaling_enabled', 'scaling_method', 'scaling_factor', 'scaling_supersampling', 'scaling_sharpness', 'frame_generation_provisioned', 'frame_generation_enabled', 'automatic_dock_mode', 'fg_backend', 'optiscaler_proxy', 'frame_generation_refresh_threshold', 'base_fps_cap', 'multiplier', 'adaptive', 'adaptive_auto_base_fps_cap', 'adaptive_fractional_real_frame_priority', 'target_fps', 'adaptive_max_multiplier', 'adaptive_stable_cadence', 'gamescope_vrr_mode', 'dynamic_cadence_recovery', 'dynamic_cadence_probe_interval_seconds', 'ultra_performance', 'flow_scale', 'performance_mode', 'pacing', 'active_in', 'gpu', 'disable_mako', 'disable_hdr_exposure', 'gamescope_wsi_compatibility', 'swapchain_image_count_compatibility', 'external_vulkan_layer', 'vkbasalt_sharpening', 'vkbasalt_sharpness', 'vkbasalt_dls_denoise', 'vkbasalt_antialiasing', 'vkbasalt_shader', 'disable_steamdeck_mode', 'enable_zink', 'force_alsa_audio']
