#!/usr/bin/env python3
"""Pre-render the ring HUD's glyph atlas (developer tool; needs Pillow and the Inter font).

The Deck runs the plugin's own Python without Pillow, so the HUD renderer reads anti-aliased
glyph coverage from py_modules/gfg_plugin/hud_font_data.py, which this script writes.
Usage: tools/make_hud_font.py [--fonts /usr/share/fonts/opentype/inter]
"""
import argparse
import base64
import json
import zlib
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "py_modules" / "gfg_plugin" / "hud_font_data.py"
CHARS = "0123456789%+-~.:/ ABCDEFGHIJKLMNOPQRSTUVWXYZh−—"
# style -> (font file, size in px at scale 1.0, letter spacing in em)
STYLES = {
    "fps": ("Inter-ExtraBold.otf", 16.0, -0.02),
    "val": ("Inter-ExtraBold.otf", 12.0, -0.02),
    "ben": ("Inter-ExtraBold.otf", 11.0, -0.02),
    "sub": ("Inter-Bold.otf", 7.5, 0.06),
    "lab": ("Inter-Bold.otf", 8.5, 0.12),
}
SCALES = (1.0, 1.5, 2.0, 3.0)


def render(font_path: Path, px: float):
    font = ImageFont.truetype(str(font_path), size=max(1, round(px)))
    ascent, descent = font.getmetrics()
    glyphs = {}
    for ch in CHARS:
        advance = font.getlength(ch)
        box = font.getbbox(ch)
        w = max(1, box[2] - min(0, box[0]))
        h = ascent + descent
        img = Image.new("L", (w + 2, h), 0)
        ImageDraw.Draw(img).text((1 - min(0, box[0]), 0), ch, font=font, fill=255)
        glyphs[ch] = {"w": img.width, "h": img.height, "x0": -1 + min(0, box[0]), "adv": advance,
                      "a": base64.b64encode(img.tobytes()).decode()}
    return {"ascent": ascent, "descent": descent, "glyphs": glyphs}


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--fonts", default="/usr/share/fonts/opentype/inter")
    args = ap.parse_args()
    atlas = {}
    for name, (file, size, spacing) in STYLES.items():
        for scale in SCALES:
            entry = render(Path(args.fonts) / file, size * scale)
            entry["spacing"] = spacing * size * scale
            atlas[f"{name}@{scale}"] = entry
    blob = base64.b64encode(zlib.compress(json.dumps(atlas, separators=(",", ":")).encode(), 9)).decode()
    lines = [blob[i:i + 100] for i in range(0, len(blob), 100)]
    OUT.write_text('"""Generated by tools/make_hud_font.py from Inter (SIL Open Font License). Do not edit."""\n'
                   "DATA = (\n" + "".join(f'    "{line}"\n' for line in lines) + ")\n", encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size // 1024} KiB)")


if __name__ == "__main__":
    main()
